version: '3.8'

services:
  mysqldb:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: ilyesbh0/ilyes_5arctic7_backend:latest
    container_name: spring-backend
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/devops_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysqldb

  frontend:
    image: ilyesbh0/ilyes_5arctic7_frontend:latest
    container_name: angular-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data: